config/routes.rb
Rails.application.routes.draw do
  get 'admin_dashboard/index'
  devise_for :users

  # resources :subjects

  resources :subjects do
    member do
      get 'lecturers'
    end
  end

  resources :lecturers, only: [:index, :show, :new, :edit]

  resources :requests

  get '/get_lecturers', to: 'requests#get_lecturers'

  root "subjects#index"

  get "admin", to: "admin_dashboard#index"
  get "admin/reports", to: "admin_dashboard#reports"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lecturer.rb
class Lecturer < ApplicationRecord
  belongs_to :subject

  enum day_of_week: { monday: 0, tuesday: 1, wednesday: 2, thursday: 3, friday: 4, saturday: 5, sunday: 6 }

  validates :day_of_week, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/request.rb
class Request < ApplicationRecord
  before_validation :generate_request_code, on: :create

  belongs_to :user, foreign_key: 'user_id'
  belongs_to :subject
  belongs_to :lecturer

  # validates :request_code, presence: true
  # validates :date, presence: true

  def generate_request_code
    self.request_code = SecureRandom.hex(5)
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :lecturers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  extend Devise::Models

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :requests, foreign_key: :user_id
end

app/controllers/admin_dashboard_controller.rb
class AdminDashboardController < ApplicationController
  before_action :authenticate_admin!

  def index
    @subjects = Subject.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
  end

  def authenticate_admin!
    redirect_to root_path, alert: !user_signed_in? ? 'Please Sign in' : "Access Denied" unless current_user&.admin?
  end
end

app/controllers/lecturers_controller.rb
class LecturersController < ApplicationController
  # before_action :authenticate_admin! # Only allow admin access

  def index
    @lecturers = Lecturer.all
  end

  def show
    @lecturer = Lecturer.find(params[:id])
  end

  def new
    @lecturer = Lecturer.new
  end

  def create
    @lecturer = Lecturer.new(lecturer_params)
    if @lecturer.save
      redirect_to @lecturer, notice: 'Lecturer was successfully created.'
    else
      render :new
    end
  end

  def edit
    @lecturer = Lecturer.find(params[:id])
  end

  def update
    @lecturer = Lecturer.find(params[:id])
    if @lecturer.update(lecturer_params)
      redirect_to @lecturer, notice: 'Lecturer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @lecturer = Lecturer.find(params[:id])
    @lecturer.destroy
    redirect_to lecturers_url, notice: 'Lecturer was successfully destroyed.'
  end

  private

  def lecturer_params
    params.require(:lecturer).permit(:name, :hours, :subject_id)
  end
end

app/controllers/requests_controller.rb
# app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user! # Ensure users are authenticated

  def index
    @requests = current_user.requests
  end

  def show
    @request = current_user.requests.find(params[:id])
  end

  def new
    @request = current_user.requests.build
  end

  def create
    @request = current_user.requests.build(request_params)

    binding.irb

    if @request.save
      redirect_to @request, notice: 'Request was successfully created.'
    else
      render :new
    end
  end

  def edit
    @request = current_user.requests.find(params[:id])
  end

  def update
    @request = current_user.requests.find(params[:id])
    if @request.update(request_params)
      redirect_to @request, notice: 'Request was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @request = current_user.requests.find(params[:id])
    @request.destroy
    redirect_to requests_url, notice: 'Request was successfully destroyed.'
  end

  def get_lecturers
    subject = Subject.find(params[:subject_id])
    @lecturers = subject.lecturers
    render json: @lecturers
  end

  private

  def request_params
    params.require(:request).permit(:day_of_week, :subject_id, :lecturer_id, :start_time, :end_time)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]

  before_action :authenticate_admin!, only: [:new, :edit, :create, :update, :destroy]

  # GET /subjects or /subjects.json

  def lecturers
    subject = Subject.find(params[:id])
    lecturers = subject.lecturers

    render json: lecturers.select(:id, :name)
  end

  def index
    @subjects = Subject.all
  end

  # GET /subjects/1 or /subjects/1.json
  def show
    @lecturers = @subject.lecturers.all
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "Subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subject
    @subject = Subject.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subject_params
    params.require(:subject).permit(:name, :description)
  end
end

app/helpers/admin_dashboard_helper.rb
module AdminDashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/admin_dashboard/index.html.erb
<h1>Admin Dashboard</h1>
<hr>

<%= link_to "Add Subject", new_subject_path %>
<br>
<%= link_to "Reports", "admin/reports" %>
<hr>

<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Description</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @subjects.each do |subject| %>
    <tr>
      <th scope="row"><%= subject.id %></th>
      <td><%= subject.name %></td>
      <td><%= subject.description %></td>
      <td>
        <div class="d-flex gap-2">
          <%= link_to "Details", subject_path(subject), class: "btn btn-outline-info btn-sm" %>
          <%= link_to "Edit", edit_subject_path(subject), class: "btn btn-warning btn-sm" %>
          <%= link_to "Delete", subject_path(subject), data: { turbo_method: :delete }, class: "btn btn-danger btn-sm" %>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentsPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
  <%= render 'shared/header' %>
  <div class="container">
    <div class="mt-4">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/lecturers/edit.html.erb
<h1>Lecturers#edit</h1>
<p>Find me in app/views/lecturers/edit.html.erb</p>

app/views/lecturers/index.html.erb
<h1>Lecturers#index</h1>
<p>Find me in app/views/lecturers/index.html.erb</p>

app/views/lecturers/new.html.erb
<h1>Lecturers#new</h1>
<p>Find me in app/views/lecturers/new.html.erb</p>

app/views/lecturers/show.html.erb
<h1>Lecturers#show</h1>
<p>Find me in app/views/lecturers/show.html.erb</p>

app/views/requests/edit.html.erb
<h1>Requests#edit</h1>
<p>Find me in app/views/requests/edit.html.erb</p>

app/views/requests/index.html.erb
<h1>Requests</h1>

<hr>
<%= link_to "Create new request", new_request_path, class: "btn btn-outline-secondary btn-sm" %>
<br>
<br>
<% @requests.each do |request| %>
  <div class="card p-2 mb-2">
    <p><%= request.request_code %></p>
    <p><%= request.day_of_week %></p>
    <p><%= request.start_time %></p>
    <p><%= request.end_time %></p>
  </div>
<% end %>

app/views/requests/new.html.erb
<h1>Requests#new</h1>

<%= form_with(model: @request, url: requests_path, method: :post, class: "form") do |f| %>
  <div class="form-group">
    <%= f.label :subject_id %>
    <%= f.collection_select :subject_id, Subject.all, :id, :name, { include_blank: true }, { class: "form-control", id: "subject-selector" } %>
  </div>

  <div class="form-group">
    <%= f.label :lecturer_id %>
    <%= f.collection_select :lecturer_id, [], :id, :name, { include_blank: true }, { class: "form-control", id: "lecturer-selector" } %>
  </div>

  <div class="form-group">
    <%= f.label :day_of_week %>
    <%= f.select :day_of_week, options_for_select(Date::DAYNAMES.each_with_index.map { |day, index| [day, index] }), { include_blank: true }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :start_time %>
    <%= f.time_field :start_time, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :end_time %>
    <%= f.time_field :end_time, class: "form-control" %>
  </div>

  <%= f.submit "Submit Request", class: "btn btn-primary" %>
<% end %>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const subjectSelector = document.getElementById("subject-selector");
        const lecturerSelector = document.getElementById("lecturer-selector");

        subjectSelector.addEventListener("change", function () {
            const subjectId = subjectSelector.value;

            fetch(`/subjects/${subjectId}/lecturers`)
                .then(response => response.json())
                .then(data => {
                    lecturerSelector.innerHTML = ""; // Clear the current options
                    data.forEach(lecturer => {
                        const option = document.createElement("option");
                        option.value = lecturer.id;
                        option.text = lecturer.name;
                        lecturerSelector.add(option);
                    });
                });
        });
    });
</script>

app/views/requests/show.html.erb
<h1>Requests#show</h1>
<p>Find me in app/views/requests/show.html.erb</p>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Student Portal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/"></a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <span class="nav-link text-success fw-bold"><%= current_user.username %></span>
          </li>
          <% unless current_user.admin %>
            <li class="nav-item">
              <%= link_to "My Requests", requests_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link text-danger" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_url, class: "nav-link text-secondary" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-danger" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/subjects/_form.html.erb
<%= form_with(model: subject) do |form| %>
  <% if subject.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<div id="<%= dom_id subject %>">
  <p>
    <strong>Name:</strong>
    <%= subject.name %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= subject.description %>
  </p>

  <% if @lecturers %>
    <% @lecturers.each do |lecturer| %>
      <div class="card p-2 mb-4">
        <h3><%= lecturer.name %></h3>
        <!--      <p><%#= lecturer.start_time %></p>-->
        <!--      <p><%#= lecturer.end_time %></p>-->

        <p><strong>Day: </strong> <%= lecturer.day_of_week.capitalize %></p>
        <p><strong>Time:</strong> <%= lecturer.start_time.strftime("%H:%M") %>
          to <%= lecturer.end_time.strftime("%H:%M") %></p>
        <!--      <p><strong>Recurring Schedule:</strong>-->
        <!--        From <%#= Time.now.beginning_of_week + lecturer.day_of_week.days + lecturer.start_time.seconds_since_midnight.seconds %>-->
        <!--        to <%#= Time.now.end_of_week + lecturer.day_of_week.days + lecturer.start_time.seconds_since_midnight.seconds %>-->
        <!--      </p>-->
      </div>
    <% end %>
  <% end %>
</div>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Show this subject", @subject %> |
  <%= link_to "Back to subjects", subjects_path %>
</div>

app/views/subjects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subjects</h1>
<hr>

<div id="subjects">
  <% @subjects.each do |subject| %>
    <%= render subject %>
    <p>
      <%= link_to "See more", subject, class: "btn btn-primary btn-sm" %>
    </p>
    <hr>
  <% end %>
</div>

<p>Only Admin</p>
<%= link_to "New subject", new_subject_path %>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Back to subjects", subjects_path %>
</div>

app/views/subjects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subject %>

<div>
  <%= link_to "Edit this subject", edit_subject_path(@subject) %> |
  <%= link_to "Back to subjects", subjects_path %>

  <%= button_to "Destroy this subject", @subject, method: :delete %>
</div>